In [1]:
import pandas as pd

## creating a dataframe like what i have in sql

In [7]:
authors_data = {
    "author_id": [],
    "first_name": [],
    "last_name": [],
    "email":[],
    "nationality": [],
    
}

authors= pd.DataFrame(authors_data)
authors

Empty DataFrame
Columns: [author_id, first_name, last_name, email, nationality]
Index: []

In [8]:
book_copies_data = {
    "copy_id": [],
    "isbn": [],
    "status": [],
    
}

book_copies= pd.DataFrame(book_copies_data)
book_copies

Empty DataFrame
Columns: [copy_id, isbn, status]
Index: []

In [10]:
book_loans_data = {
    "loan_id": [],
    "isbn": [],
    "member_id": [],
    "borrowed_date":[],
    "due_date": [],
    "returned_date": []
    
}

book_loans= pd.DataFrame(book_loans_data)
book_loans

Empty DataFrame
Columns: [loan_id, isbn, member_id, borrowed_date, due_date, returned_date]
Index: []

In [11]:
books_data = {
    "isbn": [],
    "title": [],
    "publication_year": [],
    "language":[],
    "publisher_id": [],
    "author_id": []
    
}

books= pd.DataFrame(books_data)
books

Empty DataFrame
Columns: [isbn, title, publication_year, language, publisher_id, author_id]
Index: []

In [13]:
members_data = {
    "member_id": [],
    "first_name": [],
    "last_name": [],
    "email":[],
    "phone": [],
    "address": [],
    "join_date": []
    
}

members= pd.DataFrame(members_data)
members

Empty DataFrame
Columns: [member_id, first_name, last_name, email, phone, address, join_date]
Index: []

In [14]:
publishers_data = {
    "publisher_id": [],
    "publisher_name": [],
    "country": [],
}

publishers= pd.DataFrame(publishers_data)
publishers

Empty DataFrame
Columns: [publisher_id, publisher_name, country]
Index: []

In [15]:
schema = "liane_library"
host = "127.0.0.1"
user = "root"
password = "Ayodeji007!"
port = 3306

connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

In [16]:
authors

Empty DataFrame
Columns: [author_id, first_name, last_name, email, nationality]
Index: []

In [18]:
authors['first_name'] = ["Ayodeji", "Blessy", "Andreas", "Anna", "Kelvin"]

In [19]:
authors

   author_id first_name  last_name  email  nationality
0        NaN    Ayodeji        NaN    NaN          NaN
1        NaN     Blessy        NaN    NaN          NaN
2        NaN    Andreas        NaN    NaN          NaN
3        NaN       Anna        NaN    NaN          NaN
4        NaN     Kelvin        NaN    NaN          NaN

In [20]:
authors['last_name'] = ["Abajingin", "Asir", "Politzer", "Kuksa", "Purdom"]
authors['email'] = ["abajinginayodeji@gmail.com", "blessyasir@gmail.com", "andreaspolitzer@gmail.com", "annakuksa@gmail.com", "kelvinpurdom@gmail.com"]
authors['nationality'] = ["Nigerian", "Indian", "German", "Ukranian", "Scotish"]

In [21]:
authors

   author_id first_name  last_name                       email nationality
0        NaN    Ayodeji  Abajingin  abajinginayodeji@gmail.com    Nigerian
1        NaN     Blessy       Asir        blessyasir@gmail.com      Indian
2        NaN    Andreas   Politzer   andreaspolitzer@gmail.com      German
3        NaN       Anna      Kuksa         annakuksa@gmail.com    Ukranian
4        NaN     Kelvin     Purdom      kelvinpurdom@gmail.com     Scotish

In [23]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.3-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 653.6 kB/s eta 0:00:04
    --------------------------------------- 0.0/2.1 MB 653.6 kB/s eta 0:00:04
    --------------------------------------- 0.0/2.1 MB 653.6 kB/s eta 0:00:04
   -- ------------------------------------- 0.1/2.1 MB 595.3 kB/s eta 0:00:04
   --- ------------------------------------ 0.2/2.1 MB 737.3 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/2.1 MB 1.1 MB/s eta 0:00:02
   ------- -------------------------------- 0.4/2.1 MB 1.2 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.5 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.5 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.5 MB/s eta 0:00:02
   ----------- ---------------------------- 0.6/2.1 MB 1.2 MB/s eta 0:00:02
   ----------- ---------------------------- 0.6/2.1 MB 1.2 MB/s eta 0:00:02
   ----------- ---------------------------- 0.6/2.1 MB 1.2 MB/s eta 0:00:02
   ----------- ---------------------------- 0.6/2.1 MB 1.2 MB/s eta 0:00:02
   ----------- ---------------------------- 0.6/2.1 MB 1.2 MB/s eta 0:00:02
   ------------ --------------------------- 0.7/2.1 MB 901.1 kB/s eta 0:00:02
   ------------- -------------------------- 0.7/2.1 MB 869.1 kB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 893.0 kB/s eta 0:00:02
   --------------- ------------------------ 0.8/2.1 MB 925.8 kB/s eta 0:00:02
   ---------------- ----------------------- 0.9/2.1 MB 938.8 kB/s eta 0:00:02
   ------------------ --------------------- 1.0/2.1 MB 983.0 kB/s eta 0:00:02
   -------------------- ------------------- 1.1/2.1 MB 1.0 MB/s eta 0:00:02
   --------------------- ------------------ 1.2/2.1 MB 1.1 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 1.1 MB/s eta 0:00:01
   ------------------------- -------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 1.2 MB/s eta 0:00:01
   --------------------------- ------------ 1.5/2.1 MB 950.0 kB/s eta 0:00:01
   ---------------------------- ----------- 1.5/2.1 MB 926.3 kB/s eta 0:00:01
   ---------------------------- ----------- 1.5/2.1 MB 918.7 kB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 953.1 kB/s eta 0:00:01
   -------------------------------- ------- 1.7/2.1 MB 965.4 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.1 MB 991.0 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.1 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.0 MB/s eta 0:00:00
Downloading greenlet-3.5.3-cp312-cp312-win_amd64.whl (239 kB)
   ---------------------------------------- 0.0/239.9 kB ? eta -:--:--
   ----------- ---------------------------- 71.7/239.9 kB 1.3 MB/s eta 0:00:01
   ------------------------- -------------- 153.6/239.9 kB 1.8 MB/s eta 0:00:01
   ---------------------------------------  235.5/239.9 kB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 239.9/239.9 kB 1.5 MB/s eta 0:00:00
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.6 kB ? eta -:--:--
   ---------------------------------------- 45.6/45.6 kB 1.1 MB/s eta 0:00:00
Installing collected packages: typing-extensions, greenlet, sqlalchemy
Successfully installed greenlet-3.5.3 sqlalchemy-2.0.51 typing-extensions-4.16.0

[notice] A new release of pip is available: 23.3.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import sqlalchemy

print(sqlalchemy.__version__)

2.0.51

In [28]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.7 kB ? eta -:--:--
   -------- ------------------------------- 10.2/45.7 kB ? eta -:--:--
   ----------------------------------- ---- 41.0/45.7 kB 487.6 kB/s eta 0:00:01
   ---------------------------------------- 45.7/45.7 kB 377.4 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

[notice] A new release of pip is available: 23.3.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
import pymysql

print("PyMySQL installed successfully")

PyMySQL installed successfully

In [31]:
from sqlalchemy import create_engine
import pymysql

In [33]:
engine = create_engine(
    "mysql+pymysql://root:Ayodeji007!@localhost/liane_library"
)

connection = engine.connect()
print("Connected!")

Connected!

In [34]:


authors.to_sql('authors',
                    if_exists = 'append',
                    con = connection_string,
                    index = False)

5

In [35]:
books

Empty DataFrame
Columns: [isbn, title, publication_year, language, publisher_id, author_id]
Index: []

In [52]:
books["isbn"] = ["0000000000001", "0000000000002", "0000000000003", "0000000000004", "0000000000005"]
books["title"] = ["The Silent Map of Forgotten Roads", "When the Ocean Remembers", "The Clockmaker’s Last Secret", "Beyond the Glass Horizon", "The Garden Where Shadows Bloom"]
books["publication_year"] = [1989, 2000, 2003, 1965, 1996]
books["language"] = ["English", "English", "English", "English", "English"]
books["publisher_id"] = [1, 2, 3,4, 5 ]
books["author_id"] = [1,2,3,4,5]

books.to_sql('books',
                    if_exists = 'append',
                    con = connection_string,
                    index = False)

5

In [38]:
members

Empty DataFrame
Columns: [member_id, first_name, last_name, email, phone, address, join_date]
Index: []

In [42]:
members["first_name"] = ["Paul", "Heinrich", "Cynthia", "Jasmine", "Steven"]
members["last_name"] = ["Brenard", "Ludwig", "Ciara", "Koch", "Burner"]
members["email"] = ["Paulbrenard@gmail.com", "Heinrichludwig@gmail.com", "Cynthiaciara@gmail.com", "Jasminekoch@gmail.com", "Stevenburner@gmail.com"]
members["phone"] = ["013467373885", "015976542434", "015765435786", "015634679853", "017624005539"]
members["address"] = ["orionweg 5", "Auf dem Knüll 77", "Bielefelderstrasse 45", "Gütersloherstrasse 67", "Montcenis strasse 32" ]
members["join_date"] = pd.to_datetime([
    "23-05-2003",
    "12-04-2020",
    "13-05-2007",
    "27-06-2002",
    "25-08-2002"
], dayfirst=True)



members.to_sql('members',
                    if_exists = 'append',
                    con = connection_string,
                    index = False)

5

In [43]:
publishers

Empty DataFrame
Columns: [publisher_id, publisher_name, country]
Index: []

In [44]:
publishers["publisher_name"] = ["Horizon Press", "Blue Oak Publishing", "Emerald Leaf Books", "Alpen Verlag", "Sakura House Publishing"]
publishers["country"] = ["Unitee States", "Canada", "United Kingdom", "Germany", "Japan"]

publishers.to_sql('publishers',
                    if_exists = 'append',
                    con = connection_string,
                    index = False)

5

In [46]:
book_loans

Empty DataFrame
Columns: [loan_id, isbn, member_id, borrowed_date, due_date, returned_date]
Index: []

In [53]:
book_loans["isbn"] = ["0000000000001", "0000000000002", "0000000000003", "0000000000004", "0000000000005"]
book_loans["member_id"] = [1, 2, 3, 4, 5]
book_loans["borrowed_date"] = pd.to_datetime([
    "23-01-2026",
    "13-02-2026",
    "10-10-2025",
    "15-11-2025",
    "13-12-2025"
], dayfirst=True)

book_loans["due_date"] = pd.to_datetime([
    "23-02-2026",
    "13-03-2026",
    "10-11-2026",
    "15-12-2025",
    "13-01-2026"
], dayfirst=True)

book_loans["returned_date"] = pd.to_datetime([
    "15-03-2026",
    "12-03-2026",
    "08-11-2026",
    "16-12-2025",
    "17-01-2026"
], dayfirst=True)


book_loans.to_sql('book_loans',
                    if_exists = 'append',
                    con = connection_string,
                    index = False)

5

In [49]:
book_copies

Empty DataFrame
Columns: [copy_id, isbn, status]
Index: []

In [54]:
book_copies["isbn"] = ["0000000000001", "0000000000002", "0000000000003", "0000000000004", "0000000000005"]
book_copies["status"] = ["Available", "Available", "Available", "Available", "Available"]

book_copies.to_sql('book_copies',
                    if_exists = 'append',
                    con = connection_string,
                    index = False)

5

In [ ]:
# Define the update query
update_query = """
    UPDATE Movies
    SET MovieTitle = "Thelma & Louise"
    WHERE MovieId = 3;
"""

# Execute the update query with an explicit commit
with engine.connect() as connection:
    transaction = connection.begin()
    try:
        connection.execute(text(update_query))
        transaction.commit()
    except:
        transaction.rollback()
        raise