### Import the necessary package

In [5]:
from sqlalchemy import create_engine, text
import pandas as pd

In [7]:
schema = "liane_library"
host = "127.0.0.1"
user = "root"
password = "Ayodeji007!"
port = 3306

connection_string = (
    f"mysql+pymysql://{user}:{password}@{host}:{port}/{schema}"
)

engine = create_engine(connection_string)

### Create a function that get publishers

In [8]:
def get_publishers():
    query = """
    SELECT *
    FROM publishers
    """

    return pd.read_sql(query, engine)

In [9]:
get_publishers()

   publisher_id           publisher_name         country
0             1            Horizon Press   Unitee States
1             2      Blue Oak Publishing          Canada
2             3       Emerald Leaf Books  United Kingdom
3             4             Alpen Verlag         Germany
4             5  Sakura House Publishing           Japan

In [10]:
def get_publisher(id):
    query = text("""
        SELECT *
        FROM publishers
        WHERE publisher_id = :id
    """)

    with engine.connect() as conn:
        result = conn.execute(query, {"id": id})

        return pd.DataFrame(result.fetchall(), columns=result.keys())

In [11]:
from sqlalchemy import text
get_publisher(2)

   publisher_id       publisher_name country
0             2  Blue Oak Publishing  Canada

### Define a function that gets author

In [14]:
def get_author(author_id):
    query = text("""
        SELECT *
        FROM authors
        WHERE author_id = :author_id
    """)

    with engine.connect() as conn:
        result = conn.execute(query, {"author_id": author_id})
        return pd.DataFrame(result.fetchall(), columns=result.keys())

In [13]:
def get_authors():
    return pd.read_sql("SELECT * FROM authors", engine)

### Define a function that gets book_copies

In [16]:
def get_book_copies():
    return pd.read_sql("SELECT * FROM book_copies", engine)

get_book_copies()

   copy_id           isbn     status
0        6  0000000000001  Available
1        7  0000000000002  Available
2        8  0000000000003  Available
3        9  0000000000004  Available
4       10  0000000000005  Available

In [20]:
def get_book_copy(copy_id):
    query = text("""
        SELECT *
        FROM book_copies
        WHERE copy_id = :copy_id
    """)

    with engine.connect() as conn:
        result = conn.execute(query, {"copy_id": copy_id})
        return pd.DataFrame(result.fetchall(), columns=result.keys())

In [22]:
get_book_copy(6)

   copy_id           isbn     status
0        6  0000000000001  Available

### Define a function that gets book_loans

In [23]:
def get_book_loans():
    return pd.read_sql("SELECT * FROM book_loans", engine)

In [24]:
def get_book_loan(loan_id):
    query = text("""
        SELECT *
        FROM book_loans
        WHERE loan_id = :loan_id
    """)

    with engine.connect() as conn:
        result = conn.execute(query, {"loan_id": loan_id})
        return pd.DataFrame(result.fetchall(), columns=result.keys())

### Define a function that gets books

In [25]:
def get_book(isbn):
    query = text("""
        SELECT *
        FROM books
        WHERE isbn = :isbn
    """)

    with engine.begin() as conn:
        result = conn.execute(query, {"isbn": isbn})
        return result.fetchone()

In [26]:
def get_all_books():
    query = text("""
        SELECT *
        FROM books
    """)

    with engine.begin() as conn:
        result = conn.execute(query)
        return result.fetchall()

### Define a function that gets members

In [13]:
def get_member(member_id):
    query = text("""
        SELECT *
        FROM members
        WHERE member_id = :member_id
    """)

    with engine.begin() as conn:
        result = conn.execute(query, {"member_id": member_id})
        return result.fetchone()

In [14]:
def get_all_members():
    query = text("""
        SELECT *
        FROM members
    """)

    with engine.begin() as conn:
        result = conn.execute(query)
        return result.fetchall()